
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3
      - name: Debug username
        run: echo "USER=${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Step 2 - Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step 3 - Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

on:
 push:
  branches:
	- master

jobs:
 build:
	runs-on: ubuntu-latest

	steps:
	 - name: Step 1 - pull code to VM
	 - uses: actions/checkout@v3

	 - name: Step 2 - Login Docker Hub
	 - uses: docker/login-action@v2
	   with: 
		username: ${{ secrets.DOCKERHUB_USERNAME }}
		password: ${{ secrets.DOCKERHUB_TOKEN }}
		
	 - name: Step 3 - Build and push image
	 - uses: docker/build-push-action@v4
	   with: 
		context: . # folder 's Dockerfile
		push: true
		tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest
